import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const requiredEnvVars = [
  "NEXT_PUBLIC_PAYPAL_ENVIRONMENT",
  "NEXT_PUBLIC_PAYPAL_CLIENT_ID",
  "PAYPAL_CLIENT_SECRET",
] as const;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const missingEnvVars = requiredEnvVars.filter((name) => {
    const value = process.env[name];
    return !value || value.trim() === "";
  });

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {missingEnvVars.length > 0 && (
          <div
            role="alert"
            className="border-b border-amber-300 bg-amber-50 px-4 py-3 text-sm text-amber-900"
          >
            Missing required environment variables: {missingEnvVars.join(", ")}
          </div>
        )}
        {children}
      </body>
    </html>
  );
}
